### ISSUE TITLE
Docker image not correclty versioned

### ISSUE THREAD

**Issue by Marx2** [ori-edge/k8s_gateway#11]
I can't find image with correct version in quay.io - see https://github.com/ori-edge/k8s_gateway/issues/7
I think there should be tag with incremental number like v1.2.3, not only master/latest
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/822886/106608850-2e6e1280-6565-11eb-81ed-153725a19352.png">

**Comment by networkop** [comment]
Yep, semver'd tags will be added soon. I'll try to add automated builds too but Github's CI is a PITA to troubleshoot. We'll see how I go.

**Comment by networkop** [comment]
images are tagged from now on.
