### ISSUE TITLE
Ability to target external cluster

### ISSUE THREAD

**Issue by svvac** [ori-edge/k8s_gateway#12]
I can't seem to find a way to deploy this plugin outside a kubernetes cluster, as there is no setting for the API endpoint or credentials. Is there any workaround?

**Comment by networkop** [comment]
Yeah, it assumes credentials are provided along with the k8s service account. 
Can you elaborate on your use case? Why do you need to run it outside?

**Comment by svvac** [comment]
I have a cluster that doesn't support UDP load balancers, so I can't reliably deploy DNS on them.

**Comment by networkop** [comment]
I see. You need an equivalent of [this](https://github.com/coredns/coredns/blob/master/plugin/kubernetes/setup.go#L254) `kubeconfig` option, right?

**Comment by svvac** [comment]
Yup that should do it

**Comment by networkop** [comment]
cool. I won't have time to do this any time soon, but happy to accept PRs if you want to have a got at it.

**Comment by svvac** [comment]
I'll see what I can do when I have some spare time but my Go is not on point (don't hold your breath). Thanks for the quick reply though!
