### ISSUE TITLE
Ability to set LoadBalancer IP

### ISSUE THREAD

**Issue by Marx2** [ori-edge/k8s_gateway#14]
It would be nice to have possibility to set LoadBalancer IP address in Helm chart
Ideally having all the option like in this file
https://github.com/k8s-at-home/charts/blob/master/templates/chart/values.yaml
would be great

**Comment by networkop** [comment]
yep, helm charts are very rudimentary atm. Happy to accept PRs.

**Comment by morganchristiansson** [comment]
Fixed in chart version 1.0.1 see https://github.com/ori-edge/k8s_gateway/tree/master/charts/k8s-gateway for documentation
