### ISSUE TITLE
Provide helm chart repository

### ISSUE THREAD

**Issue by morganchristiansson** [ori-edge/k8s_gateway#16]
It can be done using GitHub pages following this (verbose) guide
https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

Just need to commit the `helm package` and enable GitHub Pages for the repo..

Also thanks this is great!

**Comment by networkop** [comment]
all done. thanks for the suggestion @morganchristiansson :tada:
