### ISSUE TITLE
`zoneFiles` not working

### ISSUE THREAD

**Issue by rgstephens** [ori-edge/k8s_gateway#171]
Specifying `zoneFiles` fails and causes the error:

```log
[WARNING] plugin/file: Failed to open "open /etc/coredns/example.db: no such file or directory": trying again in 1m0s
```

This is because the `configMap` entry for the zone file is not created in the `deployment.yml`. It should be created by the template [here](https://github.com/ori-edge/k8s_gateway/blob/cb857da8f24858dd7a58b6d8316aead10ac551ab/charts/k8s-gateway/templates/deployment.yaml#L61) but the template is looking for `{{- if .Values.zoneFile }}`.

This `if` block in the template should be replaced with the example in the CoreDNS helm template [here](https://github.com/coredns/helm/blob/46af41710eaeac2bbab9347896091b14e617c9b6/charts/coredns/templates/deployment.yaml#L154).

**Comment by networkop** [comment]
fixed in #172
