### ISSUE TITLE
Depends on Caddy

### ISSUE THREAD

**Issue by euh2** [ori-edge/k8s_gateway#2]
Tried to build coredns with k8s_gateway. But get 
```
/home/t/.local/go/pkg/mod/github.com/ori-edge/k8s_gateway@v0.0.0-20201106153604-fb1a9c38517d/setup.go:19:17: cannot use setup (type func(*"github.com/caddyserver/caddy".Controller) error) as type "github.com/coredns/caddy".SetupFunc in argument to plugin.Register
/home/t/.local/go/pkg/mod/github.com/ori-edge/k8s_gateway@v0.0.0-20201106153604-fb1a9c38517d/setup.go:35:21: cannot use c (type *"github.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.GetConfig
make: *** [Makefile:16: coredns] Error 2
```
Looks to me it somehow depends on Caddy. I don't use Caddy. I think it should work with a default coredns installation.

**Comment by networkop** [comment]
I think this is due to https://github.com/coredns/coredns/pull/4018. Will try to make necessary changes in the next few days. Thanks for reporting!

**Comment by networkop** [comment]
This is fixed in https://github.com/ori-edge/k8s_gateway/commit/cc28ab0996f7e8fa1f046900c4bb984ed0af53e7
