### ISSUE TITLE
LoadBalancer IP setting is wrong in latest chart

### ISSUE THREAD

**Issue by Marx2** [ori-edge/k8s_gateway#24]
https://github.com/ori-edge/k8s_gateway/blob/dd610d7bfe2e6428a9eeeef87ef106fcfb73f809/charts/k8s-gateway/templates/service.yaml#L22
    loadBalancerIP: {{ .Values.service.loadBalancerIP }} 
should be shifted left, at the same column as "type"

**Comment by Marx2** [comment]
I see PR for it: https://github.com/ori-edge/k8s_gateway/pull/22

**Comment by networkop** [comment]
#22 is merged
