### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by morganchristiansson** [ori-edge/k8s_gateway#25]
My k3s cluster has both amd64 and arm64 nodes. I would like docker image to be multi-arch and run on arm64.

May look into this myself I think `docker buildx` does this.

**Comment by morganchristiansson** [comment]
Had a look at upstream coredns:

- They are using a very simple Dockerfile containing go binary and certs only https://github.com/coredns/coredns/blob/master/Dockerfile#L6-L9
- They have Makefile.release and just do plain docker build https://github.com/coredns/coredns/blob/master/Makefile.release#L148
- Then use some docker manifest commands to create multi-arch image https://github.com/coredns/coredns/blob/master/Makefile.release#L172-L173

Makefile seems to support building arm64 image already?

**Comment by morganchristiansson** [comment]
I'm sorry arm64 images are pushed to quay.io already! However getting exec format error

```
$ kubectl -n k8s-gateway logs k8s-gateway-96bbdc699-bb4ps
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by networkop** [comment]
fixed in https://github.com/ori-edge/k8s_gateway/commit/6c16d9777ffc298f3d27945aa56da68e65bbdd24.
