### ISSUE TITLE
Create multi arch docker images

### ISSUE THREAD

**Issue by chalko** [ori-edge/k8s_gateway#3]
Please update your Dockerfile to support building for multiple architectures

**Comment by monstrenyatko** [comment]
I have removed the **GOARCH** from the build command, see https://github.com/monstrenyatko/k8s_gateway/commit/46a657c720e87df8baa3b2e7f101f13984f86621
This allows me to build the image for multiple platforms using `docker buildx`:
```sh
docker buildx build --progress plain --platform linux/arm/v6,linux/arm64,linux/386,linux/amd64 --tag my-registry:5000/oriedge/k8s_gateway --push
```

**Comment by networkop** [comment]
fixed in https://github.com/ori-edge/k8s_gateway/commit/a4628f2a348b4a38b997adfdd75031cf24939fc8
