### ISSUE TITLE
Helmchart: Maybe i missunderstod everything but shouldn't ttl be honored for misses as well

### ISSUE THREAD

**Issue by tpihl** [ori-edge/k8s_gateway#32]
Testing a bit and have a fairly default helm setup with:
   .:53 {
        errors
        log
        health {
            lameduck 5s
        }
        ready
        k8s_gateway "<my k8s domain>" {
          apex k8s-gateway.default
          ttl 30
        }
        prometheus 0.0.0.0:9153
        loop
        reload
        loadbalance
    }

Expected:
I would have expected a cache 30 to be in that config as well (or cache 15 to follow the standard of half success ttl

**Comment by networkop** [comment]
I used to have it in helm chart at some point but removed it for some reason. I can't clearly remember, but I think the logic was that this plugin (k8s_gateway) is doing map lookups so it doesn't necessarily need another layer of caching.

Are you saying there are scenarios when cache may be needed?

**Comment by tpihl** [comment]
Hi, no I’d prefer no caching. Just that the helm chart gave me caching that I didn’t want. But if I understand correctly, this should not be installed by helm?

**Comment by networkop** [comment]
yeah, unless there's a bug, cache should not enabled by help. https://github.com/ori-edge/k8s_gateway/blob/master/charts/k8s-gateway/templates/configmap.yaml

**Comment by tpihl** [comment]
So when the gateway plugin fail to answer, coreds default value for cache of 3600 seconds is used :(. At least for me

**Comment by networkop** [comment]
can you show an example query+response?

**Comment by tpihl** [comment]
argocd exists, banana doesnt


❯ dig argocd.<redacted> @172.16.100.254

; <<>> DiG 9.16.16 <<>> argocd.<redacted> @172.16.100.254
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32697
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: be2552acdb38b116 (echoed)
;; QUESTION SECTION:
;argocd.<redacted>.            IN      A

;; ANSWER SECTION:
argocd.<redacted>.     30      IN      A       172.16.100.253

;; Query time: 6 msec
;; SERVER: 172.16.100.254#53(172.16.100.254)
;; WHEN: sön jun 20 16:35:53 CEST 2021
;; MSG SIZE  rcvd: 93



❯ dig banana.<redacted> @172.16.100.254

; <<>> DiG 9.16.16 <<>> banana.<redacted> @172.16.100.254
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 9488
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: db93e59daf3f1190 (echoed)
;; QUESTION SECTION:
;banana.<redacted>.            IN      A

;; AUTHORITY SECTION:
<redacted>.            3600    IN      SOA     k8s-gateway.default.<redacted>. hostmaster.k8s-gateway.default.<redacted>. 12345 7200 1800 86400 3600

;; Query time: 20 msec
;; SERVER: 172.16.100.254#53(172.16.100.254)
;; WHEN: sön jun 20 16:36:05 CEST 2021
;; MSG SIZE  rcvd: 179

**Comment by networkop** [comment]
ah, I see. so if anyone tries to access the banana domain before there's an ingress for it, it gets the NXDOMAIN and caches it for 3600 seconds.
What do you see as an acceptable solution in this case? Would you want to be able to override this TTL to some lower value?

**Comment by tpihl** [comment]
I think it would make sense to go with ttl or half of ttl as seems to be standard

**Comment by networkop** [comment]
I've lowered it to the same value as gcp/aws use on their SOA records, which is 60.  feel free to re-open if it's still an issue.
