### ISSUE TITLE
Return AAAA records for Services

### ISSUE THREAD

**Issue by samip5** [ori-edge/k8s_gateway#40]
Please also support IPv6.

"Currently only supports A-type queries, all other queries result in NODATA responses."

**Comment by tobiaskohlbau** [comment]
I was in the need for IPv6 support within my setup and found k8s_gateway as a perfect solution. Externaldns does not support ipv6 neither and was a bit to much for a single node cluster.

In #93 I've proposed the needed changes to support AAAA records. Lets discuss if this changes are fitting into the project and which road to take for it to be merged.
