### ISSUE TITLE
Incompatibility with K8S 1.22

### ISSUE THREAD

**Issue by jorgeboti** [ori-edge/k8s_gateway#41]
Recently we upgrade to 1.22 K8S and extenerDNS stops working.

Logging:

pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
[ERROR] plugin/errors: 2 service.k8s.domain.local. AAAA: plugin/k8s_gateway: Could not sync required resources

K8S 1.22 announce:

A number of deprecated beta APIs have been removed in 1.22 in favor of the GA version of those same APIs. All existing objects can be interacted with via stable APIs. This removal includes beta versions of the Ingress, IngressClass, Lease, APIService, ValidatingWebhookConfiguration, MutatingWebhookConfiguration, CustomResourceDefinition, TokenReview, SubjectAccessReview, and CertificateSigningRequest APIs.

**Comment by networkop** [comment]
Thanks for reporting. The PR #21 is ready and only needs some minor updates.

**Comment by networkop** [comment]
PR is merged. Fix should be in the v0.1.8
