### ISSUE TITLE
Upstream DNS Server?

### ISSUE THREAD

**Issue by rwlove** [ori-edge/k8s_gateway#42]
Is there a way to specify an upstream DNS server in this helm chart?

I'd like to do something like this:

laptop -> pihole -> (in cluster) CoreDNS(k8s-gateway) -> local named/bind (local device resolution) -> Google DNS

Is it possible to configure CoreDNS, via this helm chart, to forward unresolved requests to an upstream NS?

**Comment by networkop** [comment]
I don't think it's currently possible but it seems like a pretty simple thing to add based on the main [coredns chart](https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml#L105). PRs are welcomed 😄

**Comment by mheuser** [comment]
You can now set 'extraZonePlugins' to add an upstream forwarder, add e.g. 'forward . 1.1.1.1'.
