### ISSUE TITLE
OpenShift route support?

### ISSUE THREAD

**Issue by matthyx** [ori-edge/k8s_gateway#46]
Hi folks,

Congratulation on this awesome plugin, which does everything we need... except supporting OpenShift.
One could argue Ingress are supported, but the way the controller works is that every Ingress gets translated into a [Route](https://docs.openshift.com/container-platform/4.8/rest_api/network_apis/route-route-openshift-io-v1.html).
So it would be nice to support those...

If there is interest, I could help with this feature, but I need guidance on how to best integrate this new object.

Thanks!

**Comment by networkop** [comment]
hey @matthyx , thanks for your kind words. I actually didn't know that openshift had a Route type and it's definitely something that  can be added to this project. 

Is there a way to test it on a non-openshift cluster, i.e. kind?

**Comment by matthyx** [comment]
Hmm, I don't think so... the Route resource is specific to OpenShift.
There should be a way to try it with https://www.okd.io/minishift/

**Comment by networkop** [comment]
I can't find any spare time to try and implement this myself but I'm happy to guide you @matthyx if you want to give it a try.

I *think* it's possible to install route CRDs and controller on a non-openshift cluster based on what I'd seen here https://github.com/openshift/router -- does this look right to you?

So you should be able to start with a kind cluster and just `apply -f router/deploy/`, can you confirm?

Most of your code would go into https://github.com/ori-edge/k8s_gateway/blob/master/kubernetes.go function and you'd need to make sure that informers for Routes are setup conditionally, i.e. if no CRDs are found, you would log a message and continue. Similar to [how kong does it](https://github.com/Kong/kubernetes-ingress-controller/blob/f5549c425c675520145314bc2806f2b81cb2e8f9/railgun/controllers/configuration/ingress_utils.go#L19) but with pure client-go (we're not using controller-runtime)

**Comment by matthyx** [comment]
For the record I can confirm kind can run the route CRD and router (once I have fixed the api versions [here](https://github.com/openshift/router/pull/349)).

However, according to [this](https://docs.openshift.com/container-platform/4.8/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-load-balancer.html), routes cannot be used with external load balancers... looks like it's done using a `LoadBalancer` service which is already covered by your plugin.

Sorry for the noise.

**Comment by matthyx** [comment]
closing
