### ISSUE TITLE
How to use as a way to have external domain names resolve from inside the cluster. (e.g. cert-manager)

### ISSUE THREAD

**Issue by reesericci** [ori-edge/k8s_gateway#5]
I don't know if i'm using it right, but i'm trying to use it to have to so that if i'm in a container and try to resolve hole.kube.home (my ingress domain), it doesn't resolve when it hits my coredns. I'm running pihole to run my dns externally so my devices can access it just fine.  I'm pointing my external dns at my metallb with traefik running on it. I want it to make all my ingress domains resolve internally. I am also using coredns instead of kube-dns. Also, kube.home is my cluster domain as well as the subdomain I use to access my services externally if that makes a difference. My domains are only accessible in my network.

Error when resolving domain:
```
$ ping hole.kube.home
ping: bad address 'hole.kube.home'
```
dig output:
```
$ dig hole.kube.home
; <<>> DiG 9.16.11 <<>> hole.kube.home
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35575
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 57f025956138daee (echoed)
;; QUESTION SECTION:
;hole.kube.home.			IN	A

;; AUTHORITY SECTION:
kube.home.		5	IN	SOA	ns1.dns.kube.home. hostmaster.dns.kube.home. 12345 7200 1800 86400 5

;; Query time: 1 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Sun Jan 24 18:34:30 UTC 2021
;; MSG SIZE  rcvd: 141
```
My corefile:
```
.:53 {
    k8s_gateway kube.home
    errors
    health {
      lameduck 5s
    }
    ready
    kubernetes kube.home in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . "/etc/resolv.conf"
    cache 30
    loop
    reload
    loadbalance
}
```
Thanks in advance,
Reese

**Comment by reesericci** [comment]
@networkop

**Comment by networkop** [comment]
@reesericci can you add `kubectl get -oyaml` of your ingress resource here?

**Comment by reesericci** [comment]
sure!
```
$ kubectl get -oyaml ingress test -n kube-system
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-f452q
    field.cattle.io/ingressState: '{"dGVzdC9rdWJlLXN5c3RlbS90ZXN0Lmt1YmUuaG9tZS8vODA=":""}'
  creationTimestamp: "2021-01-24T18:07:26Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/ingressState: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:rules: {}
    manager: Go-http-client
    operation: Update
    time: "2021-01-24T18:07:26Z"
  name: test
  namespace: kube-system
  resourceVersion: "2062316"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/ingresses/test
  uid: 8c22145b-1d6c-47f4-9766-a905cb6214e4
spec:
  rules:
  - host: test.kube.home
    http:
      paths:
      - backend:
          serviceName: traefik-dashboard
          servicePort: 80
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```
(and yes, all the commands output the same result on test.kube.home as hole.kube.home. Hole.kube.home currently doesn't work b/c I am requesting a cert and that takes the ingress offline for whatever reason)

**Comment by reesericci** [comment]
@networkop

**Comment by networkop** [comment]
is there any reason why Ingress doesn't have a loadBalancer IP assigned?

**Comment by reesericci** [comment]
Because I use traefik, only a select few have a LB IP assigned. I have 192.168.1.245 metallb IP assigned to traefik which then handles it. @networkop

**Comment by networkop** [comment]
this is strange. normally an ingress controller would assign its own loadBalancer IP to all Ingress resources managed by it. I don't have much experience with traefik, maybe it behaves differently. Is there anything else i need to know to try and replicate this locally, e.g. traefik helm values?

**Comment by reesericci** [comment]
Traefik is a reverse proxy that is an ingress that all my domains point to. 

Here are my helm values:
```
---
  defaultImage: true
  imageTag: "1.7.14"
  serviceType: "LoadBalancer"
  debug: 
    enabled: false
  rbac: 
    enabled: true
  ssl: 
    enabled: true
    enforced: false
    permanentRedirect: false
  acme: 
    enabled: false
    email: "admin@example.com"
    onHostRule: true
    staging: true
    logging: true
    challengeType: "tls-alpn-01"
  persistence: 
    enabled: true
  dashboard: 
    enabled: true
    domain: "traefik.kube.home"
    auth: 
      basic: ""
```
Deployed to kube-system namespace

**Comment by reesericci** [comment]
Basically I use 1 IP pointed a traefik which then fans out to all my services. @networkop

**Comment by reesericci** [comment]
I used techno tim's guide on youtube to install traefik and metallb. @networkop

**Comment by reesericci** [comment]
It is an ingress controller

**Comment by networkop** [comment]
ok, so it turns out that traefik's ingress controller is a bit odd. It doesn't publish it's own LB IP as in status fields of managed Ingress resources. At least not by default. It needs to be told explictly via `IngressEndpoint` config option. see [this](https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/#ingressendpoint).
So, you can  add traefik's loadBalancer service name to helm values and run helm upgrade, like this:
```
  kubernetes:
    ingressEndpoint:
      publishedService: kube-system/t-traefik
```
even if you get it wrong (if service name is auto-generated), you can always manually correct it, post-install in traefik's configmap:

```
k get cm t-traefik -oyaml | kubectl neat | grep publish
      publishedService = "kube-system/t-traefik"
```

The above should make ingress resources have some LB IP, and that should be returned by the coredns plugin.

**Comment by reesericci** [comment]
Should I publish the traefik service or metallb?

**Comment by reesericci** [comment]
@networkop

**Comment by networkop** [comment]
traefik service of type LoadBalancer.

**Comment by reesericci** [comment]
There are LB ip's assigned but still getting the same logs.
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/19589006/105765069-71a10380-5f1d-11eb-8178-e993c32126d7.png">

**Comment by reesericci** [comment]
Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-f452q
    field.cattle.io/ingressState: '{"dGVzdC9rdWJlLXN5c3RlbS90ZXN0Lmt1YmUuaG9tZS8vODA=":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.245"],"port":80,"protocol":"HTTP","serviceName":"kube-system:traefik-dashboard","ingressName":"kube-system:test","hostname":"test.kube.home","allNodes":false}]'
  creationTimestamp: "2021-01-24T18:07:26Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/ingressState: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:rules: {}
    manager: Go-http-client
    operation: Update
    time: "2021-01-24T18:07:26Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: traefik
    operation: Update
    time: "2021-01-25T20:31:46Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-01-25T20:31:47Z"
  name: test
  namespace: kube-system
  resourceVersion: "2692372"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/ingresses/test
  uid: 8c22145b-1d6c-47f4-9766-a905cb6214e4
spec:
  rules:
  - host: test.kube.home
    http:
      paths:
      - backend:
          serviceName: traefik-dashboard
          servicePort: 80
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.245
```
@networkop

**Comment by networkop** [comment]
This is what I see in my env:
```
➜  traefik k get svc

NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
exdns-k8s-gateway     LoadBalancer   10.103.23.60    172.18.0.101   53:30311/UDP                 9m23s
kube-dns              ClusterIP      10.96.0.10      <none>         53/UDP,53/TCP,9153/TCP       4h29m
t-traefik             LoadBalancer   10.101.88.99    172.18.0.100   443:31582/TCP,80:30821/TCP   3h56m
t-traefik-dashboard   ClusterIP      10.99.57.58     <none>         80/TCP                       3h56m
traefik-web-ui        ClusterIP      10.108.78.213   <none>         80/TCP                       3h55m
➜  traefik k get ingress
NAME                  CLASS    HOSTS                 ADDRESS        PORTS   AGE
t-traefik-dashboard   <none>   traefik.kube.home     172.18.0.100   80      3h56m
traefik-web-ui        <none>   traefik-ui.minikube   172.18.0.100   80      3h55m
➜  traefik dig @172.18.0.101 traefik.kube.home +short
172.18.0.100
➜  traefik k get cm exdns-k8s-gateway -oyaml | kubectl neat
apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        log
        health {
            lameduck 5s
        }
        ready
        k8s_gateway "kube.home" {
          apex dns
          ttl 300
        }
        prometheus 0.0.0.0:9153
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: exdns
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: exdns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: k8s-gateway-1.0.0
  name: exdns-k8s-gateway
  namespace: kube-system

```

You need to point your DNS resolver at the k8s_gateway loadBalancer IP (172.18.0.101 in the above example), I'm not sure if you're doing this already or not.
Another issue is that you can't have this plugin together with coredns's kubernetes. I suspect your issue is that `kubernetes` plugin is higher up the preference chain and doesn't let the `kube.home` domain queries fall through to `k8s_gateway`. 

As per the readme `k8s_gateway` is not supposed to be used together with `kubernetes`. This is done deliberatly to prevent ambiguous behaviour (who's responsible for `kube.home`?) and to prevent people from accidentally exposing their internal cluster details to the outside world.

**Comment by reesericci** [comment]
As per my issue, I'm not trying to use it as a dns server externally. I'm trying to make my ingresses resolve when I go to my external domain (as defined in my ingresses - test.kube.home) from a cluster container. How do I make k8s_gateway be higher up on the preference chain and then fall through to the kubernetes plugin?

**Comment by reesericci** [comment]
@networkop

**Comment by reesericci** [comment]
I'm using the kubernetes plugin as a replacement for kube-dns.

**Comment by networkop** [comment]
ah, i see. you need to make sure `k8s_gateway` is higher in the `plugins.cfg` when you [build](https://github.com/ori-edge/k8s_gateway#with-compile-time-configuration-file) the coredns binary

**Comment by reesericci** [comment]
ok, one sec

**Comment by networkop** [comment]
or, add the `fallthrough` option to the kubernetes plugin https://coredns.io/2017/06/08/how-queries-are-processed-in-coredns/

**Comment by reesericci** [comment]
Just did the plugin.cfg and it worked!!! (i already had created a container, so it was easy)

**Comment by reesericci** [comment]
Thank you so much, @networkop this helped a lot.
