### ISSUE TITLE
[feat request] arm version

### ISSUE THREAD

**Issue by jr0dd** [ori-edge/k8s_gateway#50]
Any chance of a 32-bit arm version?

**Comment by networkop** [comment]
yeah, that should be doable. can you try testing it first? I think all what you'd need is add another value to [this line](https://github.com/ori-edge/k8s_gateway/blob/aaa1863e2df9b08aee0eb5a4a8d59e7b48b01faa/Makefile#L6) and build a container locally.  if this works for you, feel free to open a PR

**Comment by jr0dd** [comment]
> yeah, that should be doable. can you try testing it first? I think all what you'd need is add another value to [this line](https://github.com/ori-edge/k8s_gateway/blob/aaa1863e2df9b08aee0eb5a4a8d59e7b48b01faa/Makefile#L6) and build a container locally.  if this works for you, feel free to open a PR

Oof I forgot to close this. I built it myself late last night.
