### ISSUE TITLE
Not possible to specify replicas in helm chart

### ISSUE THREAD

**Issue by alxbse** [ori-edge/k8s_gateway#51]
Currently replicas in the helm chart seem to be hard-coded to 1. I have a deployment where I would like to be able to have 2 replicas running for the purpose of availability of the k8s-gateway service. Unlike the existing support for having multiple instances serving the same zone for the purposes of satisfying upstream DNS servers in this case I want multiple pods to be backing one service.

Any reasons for this value being static in the helm chart?

**Comment by networkop** [comment]
Hi, no real reason,  just a default. feel free to do a PR
