### ISSUE TITLE
Support for Nginx VirtualServer CRs

### ISSUE THREAD

**Issue by Kaezon** [ori-edge/k8s_gateway#62]
I've been looking into nginxinc's [VirtualServer CRs](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/) as a replacement for my usual Ingress objects. One of the things I need in order to keep things running smoothly is k8s_gateway support for these objects, or perhaps CRs in general.

I'm looking at adding the feature myself, but I wanted to start a conversation to see if this would be in scope for the project and talk about implementation details.

**Comment by networkop** [comment]
Hey @Kaezon , this seems like a nice contribution to me. Would be cool to add it in.

**Comment by Kaezon** [comment]
Took me a while to get my development environment working, but I'm started on it now.
The test yamls needed a little touch-up, and Tilt is new to me, but I think I've got it now.

**Comment by Kaezon** [comment]
I thought this was going to be easy for all of 2 minutes XD
I did not realize how little documentation was available for the kubernetes-client package, and working with CRs using k8s.io/client-go/kubernetes.Interface isn't really straightforward.

I'm playing with the idea of importing [nginx-ingress configuration/v1](https://github.com/nginxinc/kubernetes-ingress/tree/v2.0.3/pkg/client/informers/externalversions/configuration/v1) directly, but I'm not sure if that would be acceptable or not.
Working on understanding how the nginx-ingress project manages their own resources so I can query them properly here.

**Comment by Kaezon** [comment]
I've managed to get a test client querying VirtualServer Hosts by importing the nginx ingress ClientSet.
I'm going to try integrating it with k8s_gateway's Gateway implementation next.

**Comment by networkop** [comment]
great!, I'm planning to finish the GatewayAPI/HTTPRoute implementation by end of this week.

**Comment by Kaezon** [comment]
Fixed that issue and now it looks like DNS is able to register and return entries for VirtualServer CR's correctly.

**Comment by Kaezon** [comment]
Tests are updated. Will look to see what docs might need to be updated tomorrow.

**Comment by networkop** [comment]
@Kaezon can you check the https://github.com/ori-edge/k8s_gateway/pull/65 ? I want to make sure it makes sense to you and is aligned with what you do before I merge.

**Comment by Kaezon** [comment]
Sure thing

**Comment by Kaezon** [comment]
Next up: resolving merge conflicts now that #65 is merged :P

**Comment by networkop** [comment]
heh, yeah , I couldn't help but rename some of the funcs along the way.

**Comment by Kaezon** [comment]
@networkop I'm not sure what priority VirtualServers should have in `orderedResources`
I had given it least priority. Do you have any opinion on where they should be?

**Comment by networkop** [comment]
the order only matters when there's an overlap. my thinking was to order them from least common to most common, i.e. if you're using VirtualServers and you happen to have an ingress with the same hostname, then you most likely would prefer VS over Ingress. 
So I'd put it anywhere above ingress.

**Comment by networkop** [comment]
closed in #69
