### ISSUE TITLE
Stopped answering SOA requests for the configured domain

### ISSUE THREAD

**Issue by hfreire** [ori-edge/k8s_gateway#63]
Hey! Loving `k8s_gateway` but I noticed that after `v0.1.5` it stops answering SOA requests for the configured domain. Are you aware of any change that could have regressed this behaviour?

One can check this by doing the following command:
```
dig +short soa @<k8s_gateway load balancer IP> <domain>
```

**Comment by networkop** [comment]
hey @hfreire I can double check. This behaviour should've been covered by [this test case](https://github.com/ori-edge/k8s_gateway/blob/master/apex_test.go#L50). Can you share your corefile?

**Comment by networkop** [comment]
I think I may have found the issue. the SOA behaviour has changed from 
https://github.com/ori-edge/k8s_gateway/blob/f965ed6850e52c059dd9b6c6c2fea745623d1218/apex.go#L19
to 
https://github.com/ori-edge/k8s_gateway/blob/405d426bf8caee6cba4176ab0fce18c3df788c58/gateway.go#L178
so should be a fairly easy change. I'm just trying to understand if this is the only thing that needs to change.

**Comment by networkop** [comment]
@hfreire can you check the above PR and see if it works (or makes sense) to you?

**Comment by hfreire** [comment]
@networkop Absolutely, let me comeback to you!

**Comment by hfreire** [comment]
@networkop It makes sense. Do we have an image that I could spin up and verify it?

**Comment by networkop** [comment]
@hfreire yep, here's the image tag: `55dd32f`

**Comment by hfreire** [comment]
@networkop Verified. Works perfectly. Got the proper answer by doing: 
```
dig +short soa @<k8s_gateway load balancer IP> <domain>
```

**Comment by hfreire** [comment]
Thanks for the fix @networkop. Are you planning on doing a chart release soon?

**Comment by networkop** [comment]
yeah, hoping to get it released this week. i wanted to merge another pr (httpRoute) before doing the release

**Comment by networkop** [comment]
@hfreire release v0.2.0 is out
