### ISSUE TITLE
Versioned Docker image

### ISSUE THREAD

**Issue by Marx2** [ori-edge/k8s_gateway#7]
There should be concrete version number (semver) of docker image instead of just "latest". It allows to play nicely with GitOps approach

**Comment by networkop** [comment]
fixed in https://github.com/ori-edge/k8s_gateway/commit/7d32bc69ef7fd9cab46d60a5813a9acb8d85f23d

**Comment by Marx2** [comment]
I can't find image in quay.io
I think there should be tag with incremental number like v1.2.3, not only master/latest
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/822886/106469778-036dbb00-64a0-11eb-856c-8e5c103163a0.png">

**Comment by Marx2** [comment]
Latest version again isn't reelased with semver version number, only "latest" and SHA tags
