### ISSUE TITLE
Request: allow to have a configuration to store other types of records

### ISSUE THREAD

**Issue by trenta3** [ori-edge/k8s_gateway#79]
> Currently only supports A-type queries, all other queries result in NODATA responses

It would be great if the plugin could support other record types, like MX types, in an external configuration file.

**Comment by networkop** [comment]
I think it should be possible, using `fallthrough` . If you add it to the plugin config, any non-matched requests will fall through the plugin chain, so you can pick them up in, say, `file` plugin that relies on a static configuration file.

**Comment by trenta3** [comment]
Thank you! I managed to do it. Didn't know about the `file` plugin.
