### ISSUE TITLE
Helm chart is broken

### ISSUE THREAD

**Issue by Marx2** [ori-edge/k8s_gateway#8]
After latest changes Helm chart is broken. I've tried to use
`# Limit what kind of resources to watch, e.g. resources: ["Ingress"]`
but the format is incorrect

**Comment by networkop** [comment]
what error are you getting? I've tried it locally before pushing and it seemed to work.

**Comment by networkop** [comment]
ah, yeah, I've used the same value as `Deployment.spec.template.spec.containers[0].resources`, my bad
