### ISSUE TITLE
Split-Domains

### ISSUE THREAD

**Issue by tuxpeople** [ori-edge/k8s_gateway#94]
This is not an issue, more like a question for clarification.

Let's say we have `domain=example.com`. In our Kubernetes cluster, we have an ingress `service-a.example.com`. If I set the DNS for `example.com` to the `k8s_gateway` LoadBalancer IP, I can resolve that. So far, so good. What if I have something like `service-b.example.com` which is not in that cluster but somewhere else? Right now, in my setup, I can't resolve `service-b.example.com`. Which makes sense, as `k8s_gateway` has no idea that `service-b.example.com` exists.

I read trough the readme, but I'm not sure how to solve it. Sure, I could split the zone and put anything inside the Kubernetes cluster into a dedicated subdomain. But I'd like to keep both in the same domain. Can I use `fallthrough` for this? For me, it's not clear what exactly `fallthrough` does. Maybe it's caused by a lack of understanding Kubernetes DNS.

I'd appreciate if someone could enlighten me :-)

**Comment by tuxpeople** [comment]
Looks like `fallthrough` doesn't help in that case.

**Comment by tuxpeople** [comment]
This is the log:

```
[INFO] 10.20.30.225:63526 - 53640 "A IN service-a.example.com. udp 52 false 4096" NOERROR qr,aa,rd 80 0.000165805s
[INFO] 10.20.30.225:58596 - 41174 "A IN service-b.example.com. udp 53 false 4096" - - 0 0.000064347s
[ERROR] plugin/errors: 2 rservice-b.example.com. A: plugin/loop: no next plugin found
```

I understand that `fallthrough` is rotating trough the plugins. Question: Is there a plugin to look up external DNS servers?

**Comment by networkop** [comment]
yep, fallthrough should help with this. You just need to make sure you've got another plugin down the chain that can pick up and answer this query. For example, you can use the `forward` plugin to send fallthrough queries to a list of resolvers from your /etc/resolv.conf or any external DNS resolver. For an example, you can have a look at the configMap for the internal CoreDNS instance, which uses forward to resolve internet-bound queries

**Comment by tuxpeople** [comment]
I first unsuccessfully tried to add a plugin to coredns, until I saw in the chart that I'm able to extend `k8s_gateway`. This change seems to to work as expected:
https://github.com/tuxpeople/k8s-homelab/commit/a049f4032686c86c5fdf3ce68bc5d299f79bd2d9
